# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Change your personal monitor setup in here to keep the main config portable
source = ~/.config/hypr/monitors.conf

# Default applications
$terminal = ghostty
$fileManager = nautilus --new-window
$browser = chromium --new-window --ozone-platform=wayland
$music = spotify
$passwordManager = 1password
$messenger = signal-desktop
$webapp = $browser --app
$emailClient = thunderbird

# Use defaults Omarchy defaults
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Extra autostart processes (uncomment to run Dropbox)
# exec-once = dropbox-cli start

# Autostart applications
exec-once = [workspace 1 silent] $terminal 
exec-once = [workspace 1 silent] $browser --ozone-platform=wayland
exec-once = [workspace 2 silent] $passwordManager
exec-once = [workspace 2 silent] $emailClient

# Bind autostart
windowrule = workspace 2, class:$passwordManager
windowrule = workspace 2, class:$emailClient

# Extra env variables
env = GDK_SCALE,2 # Change to 1 if on a 1x display

# Extra bindings
bind = SUPER, A, exec, $webapp="https://chatgpt.com"
bind = SUPER, C, exec, $emailClient 
bind = SUPER, E, exec, $emailClient 
bind = SUPER, Y, exec, $webapp="https://youtube.com/"
bind = SUPER SHIFT, W, exec, $webapp="https://web.whatsapp.com/"

# Screenshots
bind = , Home, exec, ~/.local/share/omarchy/bin/omarchy-cmd-screenshot
bind = SHIFT, Home, exec, ~/.local/share/omarchy/bin/omarchy-cmd-screenshot window
bind = CTRL, Home, exec, ~/.local/share/omarchy/bin/omarchy-cmd-screenshot output

bind = , Delete, exec, ~/.local/share/omarchy/bin/omarchy-cmd-screenrecord
bind = SHIFT, Delete, exec, ~/.local/share/omarchy/bin/omarchy-cmd-screenrecord output


# Colour picke
bind = SUPER, Home, exec, hyprpicker -a

# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Alt + Space
  # kb_layout = us,dk
  # kb_options = compose:caps,grp:alt_space_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35

  touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# Scroll faster in the terminal
windowrule = scrolltouchpad 1.5, class:Alacritty

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
